apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: todo-app-golden-path
  title: "Todo App \u2014 Three Horizons Golden Path"
  description: |
    Full-stack Todo application with React 18 + TypeScript + Vite + Tailwind (frontend),
    Node.js + Express + Prisma + Redis + Winston (backend), Terraform for Azure infrastructure,
    and Playwright for E2E testing.

    Includes GitHub Codespaces dev environment, 8 Copilot agents, chaos engineering endpoints,
    and CI/CD pipelines for Azure deployment.
  tags:
    - react
    - nodejs
    - typescript
    - terraform
    - azure
    - three-horizons
    - golden-path
    - playwright
    - prisma
    - sre
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - title: Three Horizons Platform
      url: https://github.com/3horizons
      icon: github
spec:
  owner: group:default/platform-engineering
  type: service

  parameters:
    # ── Page 1: App Details ──────────────────────────────────────────────
    - title: App Details
      required:
        - name
        - description
        - owner
        - system
      properties:
        name:
          title: Application Name
          type: string
          description: Unique name for the application (lowercase, hyphens allowed)
          pattern: "^[a-z][a-z0-9-]{2,20}$"
          ui:autofocus: true
          ui:help: "Must start with a letter, 3-21 chars, lowercase alphanumeric and hyphens only"
        description:
          title: Description
          type: string
          description: Brief description of what this application does
          default: Full-stack Todo application built with the Three Horizons Golden Path
        owner:
          title: Owner
          type: string
          description: Team or user that owns this application
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: System this component belongs to
          default: three-horizons
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System

    # ── Page 2: Infrastructure Configuration ─────────────────────────────
    - title: Infrastructure Configuration
      required:
        - environment
        - azure_region
      properties:
        environment:
          title: Environment
          type: string
          description: Target deployment environment
          enum:
            - dev
            - staging
            - prod
          default: dev
          enumNames:
            - "Development"
            - "Staging"
            - "Production"
        azure_region:
          title: Azure Region
          type: string
          description: Azure region for resource deployment (brazilsouth default for LGPD compliance)
          enum:
            - brazilsouth
            - eastus2
            - westeurope
          default: brazilsouth
          enumNames:
            - "Brazil South (LGPD)"
            - "East US 2"
            - "West Europe"
        enable_redis:
          title: Enable Redis Cache
          type: boolean
          description: Enable Redis for caching and session management
          default: true
        enable_monitoring:
          title: Enable Monitoring
          type: boolean
          description: Enable Application Insights and Log Analytics
          default: true
        trigger_infra_plan:
          title: Trigger Infrastructure Plan
          type: boolean
          description: |
            Run 'terraform plan' after repo creation.
            Requires ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_SUBSCRIPTION_ID,
            ARM_TENANT_ID, POSTGRES_ADMIN_PASSWORD, ALERT_EMAIL secrets
            to be configured in the new repo's Settings → Secrets.
          default: false

    # ── Page 3: Repository Settings ──────────────────────────────────────
    - title: Repository Settings
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - 3horizons
        visibility:
          title: Repository Visibility
          type: string
          description: GitHub repository visibility
          enum:
            - private
            - public
          default: private
          enumNames:
            - "Private"
            - "Public"

  steps:
    # ── Step 1: Fetch skeleton (repo is the template) ────────────────────
    - id: fetchBase
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: "./"
        templateFileExtension: ".njk"
        copyWithoutTemplating:
          - "**/*.png"
          - "**/*.jpg"
          - "**/*.ico"
          - "**/*.woff"
          - "**/*.woff2"
          - "**/*.ttf"
          - "**/node_modules/**"
          - "**/.git/**"
          - "**/package-lock.json"
          - "**/pnpm-lock.yaml"
          - "**/*.lock"
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          environment: ${{ parameters.environment }}
          azure_region: ${{ parameters.azure_region }}
          enable_redis: ${{ parameters.enable_redis }}
          enable_monitoring: ${{ parameters.enable_monitoring }}
          orgName: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
          repoName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
          visibility: ${{ parameters.visibility }}
          trigger_infra_plan: ${{ parameters.trigger_infra_plan }}

    # ── Step 2: Publish to GitHub ────────────────────────────────────────
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: ${{ parameters.repoUrl }}
        description: "${{ parameters.description }}"
        defaultBranch: main
        repoVisibility: ${{ parameters.visibility }}
        protectDefaultBranch: true
        topics:
          - three-horizons
          - golden-path
          - todo-app
          - ${{ parameters.environment }}

    # ── Step 3: Create deployment environment in GitHub ───────────────────
    - id: createEnvironment
      name: Setup GitHub Environment
      action: github:environment:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        name: ${{ parameters.environment }}

    # ── Step 4: Trigger infrastructure plan (optional) ───────────────────
    - id: triggerInfra
      name: Deploy Infrastructure
      if: ${{ parameters.trigger_infra_plan }}
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        workflowId: infrastructure-deploy.yml
        branchOrTagName: main
        inputs:
          action: plan
          environment: ${{ parameters.environment }}

    # ── Step 5: Register in catalog ──────────────────────────────────────
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    # ── Step 6: Setup instructions ────────────────────────────────────────
    - id: setupInstructions
      name: Setup Instructions
      action: debug:log
      input:
        message: |
          ✅ Repository created: ${{ steps.publish.output.remoteUrl }}
          ✅ GitHub Environment '${{ parameters.environment }}' configured
          ✅ Codespaces ready: https://codespaces.new/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}?quickstart=1

          📋 To enable Azure infrastructure deployment, add these secrets to the repo:
          → Settings → Secrets and variables → Actions → New repository secret

          Required secrets:
            ARM_CLIENT_ID        - Azure Service Principal App ID
            ARM_CLIENT_SECRET    - Azure Service Principal Secret
            ARM_SUBSCRIPTION_ID  - Azure Subscription ID
            ARM_TENANT_ID        - Azure Tenant ID
            POSTGRES_ADMIN_PASSWORD - PostgreSQL admin password
            ALERT_EMAIL          - Email for alerts

          Then run: Actions → Infrastructure Deploy → Run workflow → action: apply

  output:
    links:
      - title: "Open Repository"
        icon: github
        url: ${{ steps.publish.output.remoteUrl }}
      - title: "Launch in GitHub Codespaces"
        icon: github
        url: "https://codespaces.new/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}?quickstart=1"
      - title: "Open in Catalog"
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: "Azure Portal"
        icon: cloud
        url: "https://portal.azure.com"
      - title: "Setup Azure Secrets"
        icon: docs
        url: "${{ steps.publish.output.remoteUrl }}/settings/secrets/actions"
